version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d/
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main_database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    # uncomment following lines to access db locally
    ports:
      - 3306:3306

volumes:
  mariadb-data:
