version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - backend
    networks:
      - cook-master-network

  backend:
    build: ./backend
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      - cook-master-network
    
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main_database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    networks:
      - cook-master-network
    # uncomment following lines to access db locally
    # ports:
    #   - 3306:3306

networks:
  cook-master-network:
