version: '3'

services:
  app:
    build: .
    ports:
      - 3333:3333
    depends_on:
      - dev-db
    networks:
      - nestjs-network
  dev-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Respons11
      POSTGRES_DB: maindatabase
    ports:
      - 5432:5432
    volumes:
      - postgres-nestjs-tutorial:/var/lib/postgresql/data
    networks:
      - nestjs-network

volumes:
  postgres-nestjs-tutorial:


networks:
  nestjs-network:
