version: '3'

services:
  dev-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Respons11
      POSTGRES_DB: maindatabase
    ports:
      - 5432:5432
    volumes:
      - postgres-nestjs-tutorial:/var/lib/postgresql/data
    networks:
      - postgres-nestjs-tutorial

volumes:
  postgres-nestjs-tutorial:

networks:
  postgres-nestjs-tutorial:
