version: '3'

services:
  dev-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Respons11
      POSTGRES_DB: maindatabase
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build: ./api
    ports:
      - 3333:3333
    depends_on:
      - dev-db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - app-network

volumes:
  postgres-volume:


networks:
  app-network:
